# Generated by Django 6.0.4 on 2026-05-22 03:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='contact_number',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='guardian_contact',
            field=models.CharField(max_length=11, validators=[django.core.validators.RegexValidator(regex='^\\d{11}$')]),
        ),
    ]
