# Generated by Django 4.2.8 on 2026-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0002_alter_student_contact_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalrecord',
            name='diagnosis',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='medicalrecord',
            name='treatment_given',
            field=models.TextField(blank=True),
        ),
    ]
