# Generated by Django 4.2.8 on 2026-05-23 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clinic', '0003_alter_medicalrecord_diagnosis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_reason',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
